# Generated by Django 4.0.3 on 2022-03-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_sequences_questions_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False, verbose_name='Answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='right_answer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='text',
        ),
        migrations.AddField(
            model_name='answers',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaires', verbose_name='Questionnaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='right_answer',
            field=models.BooleanField(default=False, verbose_name='Right answer'),
        ),
        migrations.AddField(
            model_name='answers',
            name='text',
            field=models.CharField(default=123, max_length=255, verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='header',
            field=models.CharField(default=123, max_length=255, verbose_name='Header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questions', verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaires', verbose_name='Sequence'),
        ),
        migrations.DeleteModel(
            name='Sequences',
        ),
        migrations.AddField(
            model_name='useranswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questions', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='useranswers',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.surveys', verbose_name='Survey'),
        ),
    ]
